import { StudentProfile } from "@/types";

export const sampleProfile = {
  id: 1,
  user_id: 101,
  title: "Mr.",
  first_name: "John",
  last_name: "Doe",
  email: "john.doe@example.com",
  mobile: "+1234567890",
  photo: "https://example.com/photo.jpg",
  dob: "1990-01-15",
  country_of_birth: "United States",
  nationality: "American",
  gender: "Male",
  address: "123 Main Street, Springfield, IL, USA",
  highest_level: "Bachelor's Degree",
  status: "Active",
  documents: "https://example.com/document.pdf",
  ple_file: "https://example.com/ple_file.pdf",
  uce_file: "https://example.com/uce_file.pdf",
  uace_file: "https://example.com/uace_file.pdf",
  a_level_combination: "Mathematics, Physics, Chemistry",
  o_level_points: "15",
  a_level_points: "18",
  academic_year: "2024/2025",
  intake: "September 2024",
  personal_statement:
    "A dedicated student aiming to pursue further studies in engineering.",
  permanent_home_address_line_1: "123 Main Street",
  permanent_home_address_line_2: "",
  permanent_home_address_line_3: "",
  permanent_home_address_postcode: "62704",
  permanent_home_address_country: "United States",
  alternative_phone_number: "+0987654321",
  contact_address_line_1: "456 Elm Street",
  contact_address_line_2: "Apt 12B",
  contact_address_line_3: "",
  contact_address_postcode: "62705",
  contact_address_country: "United States",
  disability_or_special_needs: "None",
  parental_higher_education: "Yes",
  ethnicity: "Caucasian",
  country_of_permanent_residence: "United States",
  tuition_fees_payer: "Self-funded",
  decision_influence: "University reputation and course content",
  job_title: "Software Engineer",
  employed_from: "2015-06-01",
  employed_to: "2020-12-31",
  working_hours: "Full-time",
  employer_name: "Tech Solutions Inc.",
  employer_address: "789 Tech Park, San Francisco, CA, USA",
  employer_contact: "employer@example.com",
  referee_1_full_name: "Jane Smith",
  referee_1_position: "Professor",
  referee_1_organisation: "Springfield University",
  referee_1_address: "456 University Ave, Springfield, IL, USA",
  referee_1_postcode: "62703",
  referee_1_telephone_number: "+1230984567",
  referee_1_email_address: "jane.smith@university.edu",
  referee_1_capacity_known: "Taught John during his Bachelor's program",
  referee_1_reference_file: "https://example.com/reference1.pdf",
  referee_2_full_name: "Michael Brown",
  referee_2_position: "Manager",
  referee_2_organisation: "Tech Solutions Inc.",
  referee_2_address: "789 Tech Park, San Francisco, CA, USA",
  referee_2_postcode: "94103",
  referee_2_telephone_number: "+0981234567",
  referee_2_email_address: "michael.brown@techsolutions.com",
  referee_2_capacity_known: "Supervised John at Tech Solutions",
  referee_2_reference_file: "https://example.com/reference2.pdf",
};

// Mock initial data (replace with actual data fetching logic)
export const initialData: StudentProfile = {
  id: 1,
  title: "Mr",
  first_name: "John",
  last_name: "Doe",
  email: "john.doe@example.com",
  mobile: "1234567890",
  photo: "https://example.com/photo.jpg",
  dob: "1990-01-01",
  country_of_birth: "United States",
  nationality: "American",
  gender: "Male",
  address: "123 Main St",
  highest_level: "High School",
  status: "Active",
  documents: "https://example.com/documents.pdf",
  ple_file: "https://example.com/ple.pdf",
  uce_file: "https://example.com/uce.pdf",
  uace_file: "https://example.com/uace.pdf",
  a_level_combination: "PCM",
  o_level_points: "32",
  a_level_points: "15",
  academic_year: "2023",
  intake: "September",
  personal_statement: "I am a dedicated student...",
  permanent_home_address_line_1: "456 Oak St",
  permanent_home_address_line_2: "",
  permanent_home_address_line_3: "",
  permanent_home_address_postcode: "12345",
  permanent_home_address_country: "United States",
  alternative_phone_number: "9876543210",
  contact_address_line_1: "789 Pine St",
  contact_address_line_2: "",
  contact_address_line_3: "",
  contact_address_postcode: "54321",
  contact_address_country: "United States",
  disability_or_special_needs: "None",
  parental_higher_education: "Yes",
  ethnicity: "White",
  country_of_permanent_residence: "United States",
  tuition_fees_payer: "Self",
  decision_influence: "Personal Interest",
  job_title: "Student",
  employed_from: "2022-09-01",
  employed_to: "2023-06-30",
  working_hours: "20",
  employer_name: "University Bookstore",
  employer_address: "University Campus",
  employer_contact: "employer@example.com",
  referee_1_full_name: "Jane Smith",
  referee_1_position: "Professor",
  referee_1_organisation: "ABC University",
  referee_1_address: "University Address",
  referee_1_postcode: "98765",
  referee_1_telephone_number: "1122334455",
  referee_1_email_address: "jane.smith@abcuniversity.edu",
  referee_1_capacity_known: "Academic Advisor",
  referee_1_reference_file: "https://example.com/referee1.pdf",
  referee_2_full_name: "Bob Johnson",
  referee_2_position: "Manager",
  referee_2_organisation: "XYZ Company",
  referee_2_address: "Company Address",
  referee_2_postcode: "56789",
  referee_2_telephone_number: "5544332211",
  referee_2_email_address: "bob.johnson@xyzcompany.com",
  referee_2_capacity_known: "Former Employer",
  referee_2_reference_file: "https://example.com/referee2.pdf",
  progress: 0,
};
